### PR TITLE
Fix wow auctions endpoint

### PR DESCRIPTION
**Pull request by stephenpoole**

### CODE REVIEW

**Comment by benweier** [comment]
Thanks for your contribution @stephenpoole. You might have noticed a little activity recently and that's because I'm currently updating the library to the most recent API spec and including (long overdue) official Typescript support!

This is going to introduce a breaking change as it will support Node 10+ (and all the nice syntax that comes with ES2018) as well as remove the Community API endpoints. In the coming days I will be pushing `v4-the-one-with-typescript` branch once I've got the internals updated to enable converting all the endpoints. I'd really appreciate if you'd like to contribute to the new branch when it becomes available

**Comment by stephenpoole** [comment]
Will keep an eye out. I'm actually adding types manually right now, so it'll be a welcome change.

**Comment by rejas** [comment]
good to hear that @benweier was afraid you'd abandoned this library... any ETA on the v4-beta-branch?

**Comment by benweier** [comment]
Thanks @rejas I was hoping to have something up a few days ago but ran into some difficulty with Typescript. I'm quite new to it so the syntax on conditional types for a function has me a bit frustrated. Maybe I'll just push the branch with all my terrible TS and work it out as we go.

I've been figuring out the build process (using straight `tsc` vs something like rollup with typescript plugin). Trying to understand how other libraries create a `index.d.ts` file compared to how they use types internally (like does everything import from `index.d.ts`, are all types exported and `index.d.ts` created as part of the build process, or are they maintained separately). These questions, along with naming conventions and library interoperability, weren't easily answered by the Typescript docs or tutorials.

A few internal changes for `4.0.0` are being worked out too.. specifically switching from `axios` to `node-fetch` - I'm not satisfied with the maintenance of `axios` or some of the security vulnerabilities that have come up, and `node-fetch` is a more mature project that follows the Fetch API spec so I felt it was the better option)

**Comment by rejas** [comment]
Cant be much of help with TS, never used it myself :-( But I am looking forward to see the branch and take a look, maybe I can watch and learn too :-) 
Unfortunately, my node-app, wowfeed, will only be half as useful after this API change from blizzard since it seems they removed the character feed endpoint :-( hopefully the guild feed still provides some info....

**Comment by stephenpoole** [comment]
@benweier it's a learning process for everyone. Personally, I've been working with Typescript for abour a year and only recently started feeling like I knew what I was doing. 

> I've been figuring out the build process (using straight tsc vs something like rollup with typescript plugin)

What I've settled with is using webpack with either `ts-loader` or `awesome-typescript-loader`.

> Trying to understand how other libraries create a index.d.ts file compared to how they use types internally (like does everything import from index.d.ts, are all types exported and index.d.ts created as part of the build process, or are they maintained separately)

`index.d.ts` is the file that exposes all your types to users of your library, you don't necessarily have to create it yourself, ts can emit this for you on build with `declaration: true` in `tsconfig.json`, then you need to specify the path to it in `package.json` with the `types` property. This is generally what I've seen from other popular libraries (React for example).

> These questions, along with naming conventions and library interoperability, weren't easily answered by the Typescript docs or tutorials.

Naming convention is kind of subjective, but generally I use `@typescript-eslint/recommended` and `airbnb-base` for linting, integrated with my webpack build. As for library interoperability, if you mean importing untyped libraries, there are docs that go over defining types manually for 3rd-party libraries.

https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

Let me know if you have any further questions.

**Comment by rejas** [comment]
Any news on the ts branch @benweier ?

**Pull request closed without merging**
