### PR TITLE
4.0.0 The One With TypeScript

### PR DESCRIPTION
**Pull request by benweier**
### A complete rewrite of the library with TypeScript.

Game clients are now instantiated individually and their API methods have been renamed. If you're using TS, it should be fairly straightforward to find the relevant method matching the endpoint from the [API Reference](https://develop.battle.net/documentation), but full documentation to come.

```
import { createInstance } from 'blizzard.js/wow'

const wow = await createInstance({ key, secret })
```
```
const blizzard = require('blizzard.js')

const wow = await blizzard.wow.createInstance({ key, secret })
```

Current status:

**Core**

- [x] Create game clients
- [x] Supported regions: US, EU, SEA, KR, TW (sorry CN)
- [x] Fetch authentication tokens
- [x] Validate authentication tokens
- [x] Tests 

**WoW**

- [x] Profile APIs
- [x] Game Data APIs
- [x] Tests

**Diablo 3**

- [x] Community APIs
- [x] Game Data APIs
- [x] Tests

**Hearthstone**

- [x] Game Data APIs
- [x] Tests

**Starcraft 2**

- [x] Community APIs
- [x] Game Data APIs
- [x] Tests

**WoW Classic**

- [x] Game Data APIs
- [x] Tests

### CODE REVIEW

**Comment by rejas** [comment]
I think its missing the dist directory, when installing it with npm. 
Or its missing teh rollup config to build it after installing.

**Comment by benweier** [comment]
You're right, I'll add a `prepare` script to make sure it builds when installing from git.

**Comment by benweier** [comment]
So the first round of actual API methods, just for character profile data, have been implemented. Tests will come shortly so I guess there's no absolute guarantee they actually do anything... please let me know if I've screwed up anything with the typings

**Comment by rejas** [comment]
Thanks, trying it out now. Any changes on how to call your API (authentication and methods)?

**Comment by benweier** [comment]
Oh yeah. So a token will be fetched during `createInstance` if one isn't supplied, and an existing token will be validated if it is supplied. If the token has expired (or juuust about to expire) a new one will be fetched.

When you need to refresh an expiring token you can do so with `getApplicationToken`/`setApplicationToken`. I'm leaning towards automatically refreshing the token rather than manually leaving it up to the user but the option to get/set will stay.

```
const token = await wow.getApplicationToken()
wow.setApplicationToken(token)
```

This token applies only to non-protected game data APIs, since protected user data APIs require an access code from the [Authorization Code Flow](https://develop.battle.net/documentation/guides/using-oauth/authorization-code-flow) which is out of scope for this library. Some much better libraries by much smarter people are well equipped to handle that already. I'll make sure those protected methods expect to be called with an authorization access token.

**Comment by rejas** [comment]
Using it like this in my app:

`
const blizzard  = require('blizzard.js'),
    secret      = process.env.wowPublicKey || require('../secret.json').wowPublicKey,
    wow         = blizzard.wow.createInstance({
        key: 'e244e24098db48dfb1f4ec6d86e4aacb',
        secret: secret
    }),
    app         = {
...
`

but getting a 401 error .... key and secret are the ones from my api bnet account....

Any idea what could go wrong when getApplicationToken is using that to post?

**Comment by benweier** [comment]
Right my bad, used a post instead of get. Fixed now

**Comment by rejas** [comment]
That fixed something, now I get an 

`Cannot set property 'token' of undefined`

when calling 

`await wow.getApplicationToken()`

**Comment by benweier** [comment]
@rejas cheers, give the latest commit a try

**Comment by rejas** [comment]
Yeah, that works better. But now I remembered that Blizzard removed the feed api so I cannot get that info anymore from their endpoints :-( 
Probably only the guild feed can be retrieved....

**Comment by benweier** [comment]
All WoW and WoW Classic APIs have now been implemented. This represents the bulk of the APIs and I think sets a decent example of how to define a client for the remaining game APIs.

**Comment by benweier** [comment]
All API methods are now implemented! Boy what a journey, and it's not over yet..

What's left?
- Tests (I know.. should have been writing these alongside the methods...)
- Docs (README + generated)
- GitHub extras like Contributing Guide and Issue Template
- Changelog and Migration Guide

And then?
- Potential improvements for method parameter typings to offer more guidance (which params are become required under different scenarios)
- Is it really worth providing typings for response objects too? I've left this generic so that developers can provide their own typings to the method interface

**Pull request merged**
